### ISSUE TITLE
it down not handle line breaks. 

### ISSUE THREAD

**Issue by deepaksisodiya** [matteodf/html-to-slack#4]
[
    {
        "type": "rich_text",
        "elements": [
            {
                "type": "rich_text_section",
                "elements": [
                    {
                        "type": "text",
                        "text": "Deepak",
                        "style": {
                            "bold": true
                        }
                    }
                ]
            },
            {
                "type": "rich_text_section",
                "elements": [
                    {
                        "type": "text",
                        "text": ""
                    }
                ]
            },
            {
                "type": "rich_text_section",
                "elements": [
                    {
                        "type": "text",
                        "text": "Deepak",
                        "style": {
                            "bold": true,
                            "italic": true
                        }
                    }
                ]
            }
        ]
    }
]

after removing 

  {
                "type": "rich_text_section",
                "elements": [
                    {
                        "type": "text",
                        "text": ""
                    }
                ]
            },
            
            
            it worked

**Comment by deepaksisodiya** [comment]
[
    {
        "type": "rich_text",
        "elements": [
            {
                "type": "rich_text_section",
                "elements": [
                    {
                        "type": "text",
                        "text": "Deepak",
                        "style": {
                            "bold": true
                        }
                    }
                ]
            },
            {
                "type": "rich_text_section",
                "elements": [
                    {
                        "type": "text",
                        "text": ""
                    }
                ]
            },
            {
                "type": "rich_text_section",
                "elements": [
                    {
                        "type": "text",
                        "text": "Deepak",
                        "style": {
                            "bold": true,
                            "italic": true
                        }
                    }
                ]
            }
        ]
    }
]

**Comment by matteodf** [comment]
Hi @deepaksisodiya , can you show me the steps to reproduce the problem? What input string are you using?

**Comment by jessicafrench** [comment]
This html causes the line break issue:
`<p>Some Text</p><p>More text without line break</p><p><br></p><p>text after an empty line</p>`

Resulting blocks:
```
[
		{
			"type": "rich_text",
			"elements": [
				{
					"type": "rich_text_section",
					"elements": [
						{
							"type": "text",
							"text": "Some Text"
						}
					]
				},
				{
					"type": "rich_text_section",
					"elements": [
						{
							"type": "text",
							"text": "More text without line break"
						}
					]
				},
				{
					"type": "rich_text_section",
					"elements": [
						{
							"type": "text",
							"text": ""
						}
					]
				},
				{
					"type": "rich_text_section",
					"elements": [
						{
							"type": "text",
							"text": "text after an empty line"
						}
					]
				}
			]
		}
	]
```

I was able to work around this by replacing all "" with " " before passing the blocks to slack via the api.

**Comment by matteodf** [comment]
Hi @jessicafrench ,
Thank you for your report. I will reopen the issue and try to resolve it as soon as possible! I have also noticed that multiple paragraphs are generally handled incorrectly, as they are all displayed on the same line, can you confirm this? I will fix this as well

**Comment by matteodf** [comment]
Regarding the specific issue of empty paragraphs containing only line breaks, I have pushed a commit to clean them up. I see no reason why empty paragraphs should be useful in Slack messaging, do you? 
I will also fix the problem of paragraphs being displayed on the same line so that they wrap automatically. After doing this, it seems to me that the possible use of paragraphs like `<p><br></p>` to make them wrap is no longer necessary, but if you have use cases where it's actually needed, please let me know!

**Comment by matteodf** [comment]
Version 0.3.2 now fixes all problems. I am closing this issue now, but if you have other suggestions, feel free to open a new issue or continue the conversation here!

**Comment by GAsplund** [comment]
I believe this issue is not fully fixed, as an input such as `<p>Some text here<br/></p>` will give the following output:
```json
{
  "type": "rich_text",
  "elements": [
    {
      "type": "rich_text_section",
      "elements": [
        {
          "type": "text",
          "text": "Some text here\n"
        }
      ]
    },
    {}
  ]
}
```
causing the request to be rejected.

**Comment by jessicafrench** [comment]
I apologize for my late reply. In regards to the empty paragraphs, they allowed for a blank line in between paragraphs and improved readability in longer posts.

**Comment by matteodf** [comment]
> I believe this issue is not fully fixed, as an input such as `<p>Some text here<br/></p>` will give the following output:
> [...]
> causing the request to be rejected.

Hi @GAsplund ,
Inserting that string between tests actually gave me a different error (it inserted a double \n), but it did not add the empty object you encountered. Anyway, I fixed the bug in version 0.3.4, can you check if you still have the problem?

> I apologize for my late reply. In regards to the empty paragraphs, they allowed for a blank line in between paragraphs and improved readability in longer posts.

Hi @jessicafrench ,
No problem with the late response! In fact, thanks for the comment! I will keep it in mind for the next release and hope to release it soon.

**Comment by GAsplund** [comment]
> > I believe this issue is not fully fixed, as an input such as `<p>Some text here<br/></p>` will give the following output:
> > [...]
> > causing the request to be rejected.
> 
> Hi @GAsplund , Inserting that string between tests actually gave me a different error (it inserted a double \n), but it did not add the empty object you encountered. Anyway, I fixed the bug in version 0.3.4, can you check if you still have the problem?

It seems like I somehow mixed up my test strings, apologies for that. I retried and found that `<p>Some text here</p><br/>` generates that output. Now that I've looked into it further it seems like it's not just limited to stray `<br/>` tags, but all illegal tags (such as `<test></test>`) generate these objects. I felt that this belongs in its own issue, so I will create a new issue for this

**Comment by matteodf** [comment]
Hi @jessicafrench ,
I just wanted to let you know that I have included your suggestion in [README.md](https://github.com/matteodf/html-to-slack/blob/8eee1fa53a3580ee03011216cecce28edac3aff0/README.md?plain=1#L50) as one of the improvements to be made in future releases. I am closing the issue since the problem seems to be fixed. If you have other suggestions or experience other problems, feel free to report them in a new issue!
